[package]
name = "done"
version = "0.1.1"
edition = "2021"
keywords = ["todo", "cli", "tui", "terminal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19.0"
crossterm = "0.26.1"
